### ISSUE TITLE
Fresh Install Using ./CODES.sh -f

### ISSUE THREAD

**Issue by kazhuyo** [FreedomBen/canvas-development-tools#14]
Fresh Install get this error :

Error: Cannot find module 'i18nliner/dist/lib/extractors/translate_call'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/canvas/node_modules/i18nliner-handlebars/dist/lib/t_call.js:5:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
module.js:471
    throw err;
    ^

Any idea howto solve this ?

**Comment by FreedomBen** [comment]
first thing I'd check is your node version.  what does:

    node -v

give you?

**Comment by kazhuyo** [comment]
Solved run this command "npm install i18nliner --save" inside canvas directory.
